apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastmcp-data-pvc
  namespace: fastmcp-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi