apiVersion: v1
kind: Service
metadata:
  name: fastmcp-service
  namespace: fastmcp-server
spec:
  type: ClusterIP
  selector:
    app: fastmcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080